require 'rubygems'
require 'rake'

file '../InspectionSchedulerIpad/build/Debug-iphonesimulator/UICatalog.app/UICatalog' do
  sh 'cd ../InspectionSchedulerIpad && xcodebuild -target UICatalog -configuration Debug -sdk iphonesimulator3.2'
end
task :app => '../InspectionSchedulerIpad/build/Debug-iphonesimulator/InspectionSchedulerIpad.app/InspectionSchedulerIpad'
task :features => :app

task :lib do
  sh 'cd ext/iCuke && rake'
end

begin
  require 'cucumber/rake/task'
  Cucumber::Rake::Task.new(:features)

  task :features => [:app, :lib]
rescue LoadError
  task :features do
    abort "Cucumber is not available. In order to run features, you must: sudo gem install cucumber"
  end
end

task :default => :features

require 'rake/rdoctask'
Rake::RDocTask.new do |rdoc|
  version = File.exist?('VERSION') ? File.read('VERSION') : ""

  rdoc.rdoc_dir = 'rdoc'
  rdoc.title = "iCuke #{version}"
  rdoc.rdoc_files.include('README*')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

task :launch => [:app, :lib] do
  require 'lib/icuke/simulator'

  simulator = ICuke::Simulator.new
  simulator.launch File.expand_path('app/iCuke/build/Debug-iphonesimulator/iCuke.app'),
    :env => { 'DYLD_INSERT_LIBRARIES' => File.expand_path(File.dirname(__FILE__) + '/ext/iCuke/libicuke.dylib') }
end

task :replay => :launch do
  simulator = ICuke::Simulator.new
  simulator.load(File.expand_path(File.dirname(__FILE__) + '/events.plist'))
  simulator.play
end

task :debug => [:app, :lib] do
  require 'lib/icuke/simulator'

  simulator = ICuke::Simulator.new
  simulator.launch File.expand_path('app/iCuke/build/Debug-iphonesimulator/iCuke.app'),
    :env => { 'DYLD_INSERT_LIBRARIES' => File.expand_path(File.dirname(__FILE__) + '/ext/iCuke/libicuke.dylib') },
    :debugger => true
  puts `ps aux|grep [i]Cuke.app/iCuke`
end
